export const medicationData = [
  {
    externalId: "AH-001",
    name: "Cetirizine",
    genericName: "Cetirizine HCl",
    brandNames: "Zyrtec, Aller-Tec",
    category: "Antihistamine",
    subCategory: "2nd Gen Oral",
    route: "Oral",
    standardDose: "1 tablet daily",
    availableStrengths: "5mg, 10mg",
    defaultFrequency: "Once daily",
    indicatedFor: "Allergic Rhinitis, Urticaria, Allergic Conjunctivitis",
    rxOtc: "OTC",
    clinicalNotes: "Non-sedating. Most common first-line antihistamine for allergy patients."
  },
  {
    externalId: "AH-002",
    name: "Loratadine",
    genericName: "Loratadine",
    brandNames: "Claritin, Alavert",
    category: "Antihistamine",
    subCategory: "2nd Gen Oral",
    route: "Oral",
    standardDose: "1 tablet daily",
    availableStrengths: "5mg, 10mg",
    defaultFrequency: "Once daily",
    indicatedFor: "Allergic Rhinitis, Urticaria",
    rxOtc: "OTC",
    clinicalNotes: "Non-sedating. Safe in pregnancy (Category B)."
  },
  {
    externalId: "AH-003",
    name: "Fexofenadine",
    genericName: "Fexofenadine HCl",
    brandNames: "Allegra",
    category: "Antihistamine",
    subCategory: "2nd Gen Oral",
    route: "Oral",
    standardDose: "1 tablet once or twice daily",
    availableStrengths: "60mg, 120mg, 180mg",
    defaultFrequency: "Once or twice daily",
    indicatedFor: "Allergic Rhinitis, Chronic Urticaria",
    rxOtc: "OTC",
    clinicalNotes: "Least sedating antihistamine. 180mg once daily or 60mg twice daily."
  },
  {
    externalId: "AH-004",
    name: "Desloratadine",
    genericName: "Desloratadine",
    brandNames: "Clarinex",
    category: "Antihistamine",
    subCategory: "2nd Gen Oral",
    route: "Oral",
    standardDose: "1 tablet daily",
    availableStrengths: "2.5mg, 5mg",
    defaultFrequency: "Once daily",
    indicatedFor: "Allergic Rhinitis, Chronic Urticaria",
    rxOtc: "Rx",
    clinicalNotes: "Active metabolite of loratadine."
  },
  {
    externalId: "AH-005",
    name: "Levocetirizine",
    genericName: "Levocetirizine HCl",
    brandNames: "Xyzal",
    category: "Antihistamine",
    subCategory: "2nd Gen Oral",
    route: "Oral",
    standardDose: "1 tablet daily (evening)",
    availableStrengths: "2.5mg, 5mg",
    defaultFrequency: "Once daily (evening)",
    indicatedFor: "Allergic Rhinitis, Chronic Urticaria",
    rxOtc: "OTC",
    clinicalNotes: "Active enantiomer of cetirizine. Take in evening."
  },
  {
    externalId: "AH-006",
    name: "Diphenhydramine",
    genericName: "Diphenhydramine HCl",
    brandNames: "Benadryl",
    category: "Antihistamine",
    subCategory: "1st Gen Oral",
    route: "Oral",
    standardDose: "25-50mg every 4-6 hours",
    availableStrengths: "12.5mg, 25mg, 50mg",
    defaultFrequency: "Every 4-6 hours",
    indicatedFor: "Allergic Reactions, Urticaria, Anaphylaxis adjunct",
    rxOtc: "OTC",
    clinicalNotes: "1st gen — sedating. Important for acute allergic reactions. Max 300mg/day."
  },
  {
    externalId: "AH-007",
    name: "Chlorpheniramine",
    genericName: "Chlorpheniramine Maleate",
    brandNames: "Chlor-Trimeton, Aller-Chlor",
    category: "Antihistamine",
    subCategory: "1st Gen Oral",
    route: "Oral",
    standardDose: "4mg every 4-6 hours",
    availableStrengths: "4mg, 8mg, 12mg",
    defaultFrequency: "Every 4-6 hours",
    indicatedFor: "Allergic Rhinitis, Urticaria",
    rxOtc: "OTC",
    clinicalNotes: "1st gen — sedating. Often used in combination cold/allergy products."
  },
  {
    externalId: "AH-008",
    name: "Hydroxyzine",
    genericName: "Hydroxyzine HCl/Pamoate",
    brandNames: "Atarax, Vistaril",
    category: "Antihistamine",
    subCategory: "1st Gen Oral",
    route: "Oral",
    standardDose: "25-100mg 3-4x daily",
    availableStrengths: "10mg, 25mg, 50mg, 100mg",
    defaultFrequency: "3-4 times daily",
    indicatedFor: "Chronic Urticaria, Pruritus, Anxiety",
    rxOtc: "Rx",
    clinicalNotes: "Significant sedation. Often used for chronic urticaria."
  },
  {
    externalId: "AH-009",
    name: "Bilastine",
    genericName: "Bilastine",
    brandNames: "Blexten, Bilaxten",
    category: "Antihistamine",
    subCategory: "2nd Gen Oral",
    route: "Oral",
    standardDose: "20mg once daily",
    availableStrengths: "20mg",
    defaultFrequency: "Once daily (empty stomach)",
    indicatedFor: "Allergic Rhinitis, Urticaria",
    rxOtc: "Rx",
    clinicalNotes: "Newer 2nd gen. Take on empty stomach — food reduces absorption."
  },
  {
    externalId: "AH-010",
    name: "Rupatadine",
    genericName: "Rupatadine",
    brandNames: "Rupall",
    category: "Antihistamine",
    subCategory: "2nd Gen Oral",
    route: "Oral",
    standardDose: "10mg once daily",
    availableStrengths: "10mg",
    defaultFrequency: "Once daily",
    indicatedFor: "Allergic Rhinitis, Chronic Urticaria",
    rxOtc: "Rx",
    clinicalNotes: "Also has PAF antagonist activity."
  },
  {
    externalId: "NS-001",
    name: "Fluticasone Propionate",
    genericName: "Fluticasone Propionate",
    brandNames: "Flonase Allergy Relief, Beconase",
    category: "Nasal Spray",
    subCategory: "Intranasal Corticosteroid",
    route: "Intranasal",
    standardDose: "2 sprays per nostril once daily (50mcg/spray)",
    availableStrengths: "50mcg/spray",
    defaultFrequency: "Once daily",
    indicatedFor: "Allergic Rhinitis, Nasal Polyps",
    rxOtc: "OTC",
    clinicalNotes: "First-line treatment for allergic rhinitis. Most prescribed nasal spray."
  },
  {
    externalId: "NS-002",
    name: "Fluticasone Furoate",
    genericName: "Fluticasone Furoate",
    brandNames: "Flonase Sensimist, Veramyst",
    category: "Nasal Spray",
    subCategory: "Intranasal Corticosteroid",
    route: "Intranasal",
    standardDose: "2 sprays per nostril once daily (27.5mcg/spray)",
    availableStrengths: "27.5mcg/spray",
    defaultFrequency: "Once daily",
    indicatedFor: "Allergic Rhinitis",
    rxOtc: "OTC",
    clinicalNotes: "Gentler formulation — good for sensitive nasal passages. Less drip."
  },
  {
    externalId: "NS-003",
    name: "Triamcinolone Acetonide",
    genericName: "Triamcinolone Acetonide",
    brandNames: "Nasacort Allergy 24HR",
    category: "Nasal Spray",
    subCategory: "Intranasal Corticosteroid",
    route: "Intranasal",
    standardDose: "2 sprays per nostril once daily (55mcg/spray)",
    availableStrengths: "55mcg/spray",
    defaultFrequency: "Once daily",
    indicatedFor: "Allergic Rhinitis",
    rxOtc: "OTC",
    clinicalNotes: "Steroid-free propellant. Good for patients sensitive to preservatives."
  },
  {
    externalId: "NS-004",
    name: "Budesonide",
    genericName: "Budesonide",
    brandNames: "Rhinocort Allergy",
    category: "Nasal Spray",
    subCategory: "Intranasal Corticosteroid",
    route: "Intranasal",
    standardDose: "1-4 sprays per nostril once daily (32mcg/spray)",
    availableStrengths: "32mcg/spray",
    defaultFrequency: "Once daily",
    indicatedFor: "Allergic Rhinitis, Nasal Polyps",
    rxOtc: "OTC",
    clinicalNotes: "Safe in pregnancy (Category B). Often first choice in pregnant patients."
  },
  {
    externalId: "NS-005",
    name: "Mometasone Furoate",
    genericName: "Mometasone Furoate",
    brandNames: "Nasonex",
    category: "Nasal Spray",
    subCategory: "Intranasal Corticosteroid",
    route: "Intranasal",
    standardDose: "2 sprays per nostril once daily (50mcg/spray)",
    availableStrengths: "50mcg/spray",
    defaultFrequency: "Once daily",
    indicatedFor: "Allergic Rhinitis, Nasal Polyps",
    rxOtc: "Rx",
    clinicalNotes: "Low systemic bioavailability. Also indicated for nasal polyps."
  },
  {
    externalId: "NS-006",
    name: "Beclomethasone Dipropionate",
    genericName: "Beclomethasone Dipropionate",
    brandNames: "Beconase AQ, QNASL",
    category: "Nasal Spray",
    subCategory: "Intranasal Corticosteroid",
    route: "Intranasal",
    standardDose: "1-2 sprays per nostril twice daily (42mcg/spray)",
    availableStrengths: "42mcg/spray, 80mcg/spray",
    defaultFrequency: "Twice daily",
    indicatedFor: "Allergic Rhinitis",
    rxOtc: "Rx",
    clinicalNotes: "Older formulation. QNASL is a dry aerosol version."
  },
  {
    externalId: "NS-007",
    name: "Ciclesonide",
    genericName: "Ciclesonide",
    brandNames: "Omnaris, Zetonna",
    category: "Nasal Spray",
    subCategory: "Intranasal Corticosteroid",
    route: "Intranasal",
    standardDose: "2 sprays per nostril once daily (50mcg/spray)",
    availableStrengths: "50mcg/spray, 37mcg/spray",
    defaultFrequency: "Once daily",
    indicatedFor: "Allergic Rhinitis",
    rxOtc: "Rx",
    clinicalNotes: "Prodrug — activated in nasal tissue. Very low systemic absorption."
  },
  {
    externalId: "NA-001",
    name: "Azelastine",
    genericName: "Azelastine HCl",
    brandNames: "Astelin, Astepro Allergy",
    category: "Nasal Spray",
    subCategory: "Intranasal Antihistamine",
    route: "Intranasal",
    standardDose: "1-2 sprays per nostril twice daily (137mcg/spray)",
    availableStrengths: "137mcg/spray, 205.5mcg/spray",
    defaultFrequency: "Twice daily",
    indicatedFor: "Allergic Rhinitis, Vasomotor Rhinitis",
    rxOtc: "OTC (Astepro) / Rx",
    clinicalNotes: "Fast onset (~15 min). Can cause bitter taste/drowsiness. Rx for vasomotor rhinitis."
  },
  {
    externalId: "NA-002",
    name: "Olopatadine",
    genericName: "Olopatadine HCl",
    brandNames: "Patanase",
    category: "Nasal Spray",
    subCategory: "Intranasal Antihistamine",
    route: "Intranasal",
    standardDose: "2 sprays per nostril twice daily (665mcg/spray)",
    availableStrengths: "665mcg/spray",
    defaultFrequency: "Twice daily",
    indicatedFor: "Allergic Rhinitis",
    rxOtc: "Rx",
    clinicalNotes: "Dual action — antihistamine + mast cell stabilizer."
  },
  {
    externalId: "CN-001",
    name: "Azelastine/Fluticasone",
    genericName: "Azelastine + Fluticasone Propionate",
    brandNames: "Dymista",
    category: "Nasal Spray",
    subCategory: "Combination Intranasal",
    route: "Intranasal",
    standardDose: "1 spray per nostril twice daily",
    availableStrengths: "137mcg azelastine + 50mcg fluticasone/spray",
    defaultFrequency: "Twice daily",
    indicatedFor: "Moderate-Severe Allergic Rhinitis",
    rxOtc: "Rx",
    clinicalNotes: "Superior to either component alone for moderate-severe AR. High-end treatment."
  },
  {
    externalId: "ND-001",
    name: "Oxymetazoline",
    genericName: "Oxymetazoline HCl",
    brandNames: "Afrin, Sinex, Vicks Sinex",
    category: "Nasal Spray",
    subCategory: "Nasal Decongestant",
    route: "Intranasal",
    standardDose: "2-3 sprays per nostril every 10-12 hours",
    availableStrengths: "0.05%",
    defaultFrequency: "Every 10-12 hours (max 3 days)",
    indicatedFor: "Nasal Congestion",
    rxOtc: "OTC",
    clinicalNotes: "⚠️ MAX 3 DAYS USE — rebound congestion (rhinitis medicamentosa) if used longer."
  },
  {
    externalId: "ND-002",
    name: "Xylometazoline",
    genericName: "Xylometazoline HCl",
    brandNames: "Otrivin, Natru-Vent",
    category: "Nasal Spray",
    subCategory: "Nasal Decongestant",
    route: "Intranasal",
    standardDose: "2-3 sprays per nostril every 8-10 hours",
    availableStrengths: "0.05%, 0.1%",
    defaultFrequency: "Every 8-10 hours (max 3 days)",
    indicatedFor: "Nasal Congestion",
    rxOtc: "OTC",
    clinicalNotes: "⚠️ MAX 3 DAYS USE. 0.05% for children, 0.1% for adults."
  },
  {
    externalId: "ND-003",
    name: "Pseudoephedrine",
    genericName: "Pseudoephedrine HCl",
    brandNames: "Sudafed",
    category: "Oral",
    subCategory: "Oral Decongestant",
    route: "Oral",
    standardDose: "30-60mg every 4-6 hours",
    availableStrengths: "30mg, 60mg, 120mg XR",
    defaultFrequency: "Every 4-6 hours",
    indicatedFor: "Nasal Congestion, Sinus Congestion",
    rxOtc: "OTC (behind counter)",
    clinicalNotes: "Oral decongestant. Behind-the-counter (ID required). Avoid in hypertension/heart disease."
  },
  {
    externalId: "ND-004",
    name: "Phenylephrine",
    genericName: "Phenylephrine HCl",
    brandNames: "Neo-Synephrine, Sudafed PE",
    category: "Nasal Spray / Oral",
    subCategory: "Nasal Decongestant",
    route: "Intranasal/Oral",
    standardDose: "Spray: 2-3 sprays q4h. Oral: 10mg q4h",
    availableStrengths: "0.25%, 0.5%, 1% spray; 10mg oral",
    defaultFrequency: "Every 4 hours",
    indicatedFor: "Nasal Congestion",
    rxOtc: "OTC",
    clinicalNotes: "⚠️ Oral form has limited efficacy per recent FDA review. Nasal spray max 3 days."
  },
  {
    externalId: "ND-005",
    name: "Ipratropium Bromide",
    genericName: "Ipratropium Bromide",
    brandNames: "Atrovent Nasal",
    category: "Nasal Spray",
    subCategory: "Anticholinergic Nasal",
    route: "Intranasal",
    standardDose: "2 sprays per nostril 2-3x daily",
    availableStrengths: "0.03%, 0.06%",
    defaultFrequency: "2-3 times daily",
    indicatedFor: "Runny Nose (Rhinorrhea), Vasomotor Rhinitis",
    rxOtc: "Rx",
    clinicalNotes: "Addresses runny nose specifically — not congestion. Good for vasomotor rhinitis."
  },
  {
    externalId: "LT-001",
    name: "Montelukast",
    genericName: "Montelukast Sodium",
    brandNames: "Singulair",
    category: "Leukotriene Modifier",
    subCategory: "LTRA",
    route: "Oral",
    standardDose: "10mg once daily (adults); 5mg chewable (6-14y)",
    availableStrengths: "4mg granules, 5mg chewable, 10mg tablet",
    defaultFrequency: "Once daily (evening)",
    indicatedFor: "Allergic Rhinitis, Asthma, Exercise-Induced Bronchoconstriction",
    rxOtc: "Rx",
    clinicalNotes: "⚠️ FDA Black Box Warning: neuropsychiatric events (mood changes, suicidal thoughts). Use only if alternatives inadequate."
  },
  {
    externalId: "LT-002",
    name: "Zafirlukast",
    genericName: "Zafirlukast",
    brandNames: "Accolate",
    category: "Leukotriene Modifier",
    subCategory: "LTRA",
    route: "Oral",
    standardDose: "20mg twice daily (on empty stomach)",
    availableStrengths: "10mg, 20mg",
    defaultFrequency: "Twice daily",
    indicatedFor: "Asthma",
    rxOtc: "Rx",
    clinicalNotes: "Take 1hr before or 2hrs after meals. Monitor liver function."
  },
  {
    externalId: "LT-003",
    name: "Zileuton",
    genericName: "Zileuton",
    brandNames: "Zyflo",
    category: "Leukotriene Modifier",
    subCategory: "5-LOX Inhibitor",
    route: "Oral",
    standardDose: "600mg four times daily or 1200mg twice daily (ER)",
    availableStrengths: "600mg IR, 600mg ER",
    defaultFrequency: "4x daily (IR) or 2x daily (ER)",
    indicatedFor: "Asthma",
    rxOtc: "Rx",
    clinicalNotes: "Monitor liver enzymes. Multiple drug interactions."
  },
  {
    externalId: "IC-001",
    name: "Fluticasone Propionate Inhaler",
    genericName: "Fluticasone Propionate",
    brandNames: "Flovent HFA, Arnuity Ellipta",
    category: "Inhaled Corticosteroid",
    subCategory: "ICS — Asthma",
    route: "Inhaled (MDI/DPI)",
    standardDose: "Low: 88mcg 2x/day. Med: 176mcg 2x/day. High: 440mcg 2x/day",
    availableStrengths: "44mcg, 88mcg, 110mcg, 220mcg, 250mcg",
    defaultFrequency: "Twice daily (or once daily for Ellipta)",
    indicatedFor: "Persistent Asthma (all severities)",
    rxOtc: "Rx",
    clinicalNotes: "Gold standard ICS. Flovent HFA being discontinued — Xhance available for polyps."
  },
  {
    externalId: "IC-002",
    name: "Budesonide Inhaler",
    genericName: "Budesonide",
    brandNames: "Pulmicort Flexhaler, Pulmicort Respules",
    category: "Inhaled Corticosteroid",
    subCategory: "ICS — Asthma",
    route: "Inhaled (DPI/Nebulizer)",
    standardDose: "Low: 180mcg 2x/day. Med: 360mcg 2x/day. High: 720mcg 2x/day",
    availableStrengths: "90mcg, 180mcg (DPI); 0.25mg, 0.5mg, 1mg (nebulizer)",
    defaultFrequency: "Twice daily",
    indicatedFor: "Persistent Asthma",
    rxOtc: "Rx",
    clinicalNotes: "Safe in pregnancy. Respules for young children via nebulizer."
  },
  {
    externalId: "IC-003",
    name: "Beclomethasone Dipropionate Inhaler",
    genericName: "Beclomethasone Dipropionate",
    brandNames: "QVAR RediHaler",
    category: "Inhaled Corticosteroid",
    subCategory: "ICS — Asthma",
    route: "Inhaled (MDI)",
    standardDose: "Low: 80-160mcg/day. Med: 160-320mcg/day. High: >320mcg/day",
    availableStrengths: "40mcg, 80mcg",
    defaultFrequency: "Twice daily",
    indicatedFor: "Persistent Asthma",
    rxOtc: "Rx",
    clinicalNotes: "HFA formulation — smaller particles, better lung deposition."
  },
  {
    externalId: "IC-004",
    name: "Mometasone Furoate Inhaler",
    genericName: "Mometasone Furoate",
    brandNames: "Asmanex HFA, Asmanex Twisthaler",
    category: "Inhaled Corticosteroid",
    subCategory: "ICS — Asthma",
    route: "Inhaled (MDI/DPI)",
    standardDose: "Low: 200mcg once daily. Med: 400mcg/day. High: 400mcg+ daily",
    availableStrengths: "100mcg, 200mcg, 220mcg",
    defaultFrequency: "Once or twice daily",
    indicatedFor: "Persistent Asthma",
    rxOtc: "Rx",
    clinicalNotes: "Once-daily option improves adherence."
  },
  {
    externalId: "IC-005",
    name: "Ciclesonide Inhaler",
    genericName: "Ciclesonide",
    brandNames: "Alvesco",
    category: "Inhaled Corticosteroid",
    subCategory: "ICS — Asthma",
    route: "Inhaled (MDI)",
    standardDose: "Low: 80-160mcg/day. Med: 160-320mcg/day. High: >320mcg/day",
    availableStrengths: "80mcg, 160mcg",
    defaultFrequency: "Twice daily",
    indicatedFor: "Persistent Asthma",
    rxOtc: "Rx",
    clinicalNotes: "Prodrug activated in lung. Low oropharyngeal side effects."
  },
  {
    externalId: "LA-001",
    name: "Salmeterol",
    genericName: "Salmeterol Xinafoate",
    brandNames: "Serevent Diskus",
    category: "LABA",
    subCategory: "Long-Acting Bronchodilator",
    route: "Inhaled (DPI)",
    standardDose: "1 inhalation (50mcg) twice daily",
    availableStrengths: "50mcg",
    defaultFrequency: "Twice daily",
    indicatedFor: "Persistent Asthma (add-on to ICS), COPD",
    rxOtc: "Rx",
    clinicalNotes: "⚠️ NEVER use as monotherapy for asthma — always combine with ICS."
  },
  {
    externalId: "LA-002",
    name: "Formoterol",
    genericName: "Formoterol Fumarate",
    brandNames: "Foradil Aerolizer, Perforomist",
    category: "LABA",
    subCategory: "Long-Acting Bronchodilator",
    route: "Inhaled (DPI/Nebulizer)",
    standardDose: "1 capsule (12mcg) twice daily inhaled",
    availableStrengths: "12mcg capsule, 20mcg/2mL nebulizer",
    defaultFrequency: "Twice daily",
    indicatedFor: "Persistent Asthma (add-on), COPD, EIB",
    rxOtc: "Rx",
    clinicalNotes: "⚠️ NEVER use as monotherapy for asthma. Faster onset than salmeterol."
  },
  {
    externalId: "CL-001",
    name: "Fluticasone/Salmeterol",
    genericName: "Fluticasone Propionate + Salmeterol",
    brandNames: "Advair Diskus, Advair HFA, AirDuo",
    category: "ICS/LABA Combo",
    subCategory: "Combination Inhaler",
    route: "Inhaled (DPI/MDI)",
    standardDose: "1 inhalation twice daily",
    availableStrengths: "100/50, 250/50, 500/50 mcg (Diskus); 45/21, 115/21, 230/21 mcg (HFA)",
    defaultFrequency: "Twice daily",
    indicatedFor: "Moderate-Severe Persistent Asthma, COPD",
    rxOtc: "Rx",
    clinicalNotes: "Most prescribed combination inhaler. Don't use for acute symptoms."
  },
  {
    externalId: "CL-002",
    name: "Budesonide/Formoterol",
    genericName: "Budesonide + Formoterol Fumarate",
    brandNames: "Symbicort",
    category: "ICS/LABA Combo",
    subCategory: "Combination Inhaler",
    route: "Inhaled (MDI)",
    standardDose: "2 inhalations twice daily",
    availableStrengths: "80/4.5mcg, 160/4.5mcg",
    defaultFrequency: "Twice daily (also MART strategy)",
    indicatedFor: "Moderate-Severe Persistent Asthma, COPD",
    rxOtc: "Rx",
    clinicalNotes: "Can be used as MART (Maintenance and Reliever Therapy) strategy."
  },
  {
    externalId: "CL-003",
    name: "Mometasone/Formoterol",
    genericName: "Mometasone Furoate + Formoterol",
    brandNames: "Dulera",
    category: "ICS/LABA Combo",
    subCategory: "Combination Inhaler",
    route: "Inhaled (MDI)",
    standardDose: "2 inhalations twice daily",
    availableStrengths: "100/5mcg, 200/5mcg",
    defaultFrequency: "Twice daily",
    indicatedFor: "Moderate-Severe Persistent Asthma",
    rxOtc: "Rx",
    clinicalNotes: ""
  },
  {
    externalId: "CL-004",
    name: "Fluticasone Furoate/Vilanterol",
    genericName: "Fluticasone Furoate + Vilanterol",
    brandNames: "Breo Ellipta",
    category: "ICS/LABA Combo",
    subCategory: "Combination Inhaler",
    route: "Inhaled (DPI)",
    standardDose: "1 inhalation once daily",
    availableStrengths: "100/25mcg, 200/25mcg",
    defaultFrequency: "Once daily",
    indicatedFor: "Persistent Asthma, COPD",
    rxOtc: "Rx",
    clinicalNotes: "Once-daily dosing improves adherence significantly."
  },
  {
    externalId: "CL-005",
    name: "Beclomethasone/Formoterol",
    genericName: "Beclomethasone + Formoterol",
    brandNames: "Fostair",
    category: "ICS/LABA Combo",
    subCategory: "Combination Inhaler",
    route: "Inhaled (MDI)",
    standardDose: "2 inhalations twice daily",
    availableStrengths: "100/6mcg",
    defaultFrequency: "Twice daily",
    indicatedFor: "Moderate Persistent Asthma",
    rxOtc: "Rx",
    clinicalNotes: "Extra-fine particle formulation."
  },
  {
    externalId: "SA-001",
    name: "Albuterol (Salbutamol)",
    genericName: "Albuterol Sulfate",
    brandNames: "ProAir HFA, Ventolin HFA, Proventil HFA, ProAir RespiClick",
    category: "SABA",
    subCategory: "Rescue Bronchodilator",
    route: "Inhaled (MDI/DPI/Nebulizer)",
    standardDose: "2 puffs (90mcg/puff) every 4-6 hours PRN. Nebulizer: 2.5mg every 4-8 hours",
    availableStrengths: "90mcg MDI; 108mcg RespiClick; 0.083%, 0.5% nebulizer solution",
    defaultFrequency: "Every 4-6 hours PRN",
    indicatedFor: "Acute Asthma, Exercise-Induced Bronchoconstriction, COPD exacerbation",
    rxOtc: "Rx",
    clinicalNotes: "Most common rescue inhaler. If using >2 days/week for symptoms = poor asthma control."
  },
  {
    externalId: "SA-002",
    name: "Levalbuterol",
    genericName: "Levalbuterol HCl",
    brandNames: "Xopenex HFA, Xopenex",
    category: "SABA",
    subCategory: "Rescue Bronchodilator",
    route: "Inhaled (MDI/Nebulizer)",
    standardDose: "2 puffs (45mcg/puff) every 4-6 hours PRN. Nebulizer: 0.31mg, 0.63mg, 1.25mg every 6-8 hours",
    availableStrengths: "45mcg MDI; 0.31mg, 0.63mg, 1.25mg nebulizer",
    defaultFrequency: "Every 4-8 hours PRN",
    indicatedFor: "Acute Asthma, EIB",
    rxOtc: "Rx",
    clinicalNotes: "R-enantiomer of albuterol. May have fewer cardiovascular side effects."
  },
  {
    externalId: "SA-003",
    name: "Pirbuterol",
    genericName: "Pirbuterol Acetate",
    brandNames: "Maxair Autohaler",
    category: "SABA",
    subCategory: "Rescue Bronchodilator",
    route: "Inhaled (MDI)",
    standardDose: "2 puffs (200mcg/puff) every 4-6 hours PRN",
    availableStrengths: "200mcg",
    defaultFrequency: "Every 4-6 hours PRN",
    indicatedFor: "Acute Asthma",
    rxOtc: "Rx",
    clinicalNotes: "Breath-activated inhaler — easier for some patients."
  },
  {
    externalId: "BIO-001",
    name: "Omalizumab",
    genericName: "Omalizumab",
    brandNames: "Xolair",
    category: "Biologic",
    subCategory: "Anti-IgE",
    route: "Subcutaneous injection",
    standardDose: "150-375mg every 2-4 weeks (dose based on weight + IgE level)",
    availableStrengths: "75mg, 150mg vials/prefilled syringes",
    defaultFrequency: "Every 2-4 weeks",
    indicatedFor: "Moderate-Severe Allergic Asthma (IgE 30-1500 IU/mL, sensitized), Chronic Urticaria, Food Allergy",
    rxOtc: "Rx",
    clinicalNotes: "First biologic for asthma. Must be administered in healthcare setting (anaphylaxis risk 30 min observation). Also FDA-approved for chronic urticaria and food allergy (2024)."
  },
  {
    externalId: "BIO-002",
    name: "Mepolizumab",
    genericName: "Mepolizumab",
    brandNames: "Nucala",
    category: "Biologic",
    subCategory: "Anti-IL-5",
    route: "Subcutaneous injection",
    standardDose: "100mg every 4 weeks",
    availableStrengths: "100mg prefilled syringe",
    defaultFrequency: "Every 4 weeks",
    indicatedFor: "Severe Eosinophilic Asthma (eosinophils ≥150 cells/mcL), EGPA, HES, CRSwNP",
    rxOtc: "Rx",
    clinicalNotes: "Targets IL-5 to reduce eosinophil production. Requires eosinophil count. Can be self-injected at home."
  },
  {
    externalId: "BIO-003",
    name: "Reslizumab",
    genericName: "Reslizumab",
    brandNames: "Cinqair",
    category: "Biologic",
    subCategory: "Anti-IL-5",
    route: "Intravenous infusion",
    standardDose: "3mg/kg IV every 4 weeks",
    availableStrengths: "100mg/10mL vial",
    defaultFrequency: "Every 4 weeks (IV infusion)",
    indicatedFor: "Severe Eosinophilic Asthma (eosinophils ≥400 cells/mcL)",
    rxOtc: "Rx",
    clinicalNotes: "Weight-based IV dosing. Must be given in clinical setting. Risk of anaphylaxis."
  },
  {
    externalId: "BIO-004",
    name: "Benralizumab",
    genericName: "Benralizumab",
    brandNames: "Fasenra",
    category: "Biologic",
    subCategory: "Anti-IL-5Rα",
    route: "Subcutaneous injection",
    standardDose: "30mg every 4 weeks x3, then every 8 weeks",
    availableStrengths: "30mg prefilled syringe (Fasenra Pen)",
    defaultFrequency: "Every 4 weeks (loading) then every 8 weeks",
    indicatedFor: "Severe Eosinophilic Asthma (eosinophils ≥300 cells/mcL)",
    rxOtc: "Rx",
    clinicalNotes: "Depletes eosinophils directly (not just reduces). Every-8-week maintenance is convenient. Can be self-injected."
  },
  {
    externalId: "BIO-005",
    name: "Dupilumab",
    genericName: "Dupilumab",
    brandNames: "Dupixent",
    category: "Biologic",
    subCategory: "Anti-IL-4Rα (IL-4/IL-13)",
    route: "Subcutaneous injection",
    standardDose: "200mg or 300mg every 2 weeks (asthma); 300mg every 2 weeks (AD/CRSwNP)",
    availableStrengths: "200mg, 300mg prefilled syringe/pen",
    defaultFrequency: "Every 2 weeks",
    indicatedFor: "Moderate-Severe Eosinophilic Asthma, Atopic Dermatitis, CRSwNP, EoE, Prurigo Nodularis",
    rxOtc: "Rx",
    clinicalNotes: "Broadest indication biologic. Blocks both IL-4 and IL-13 signaling. Initial dose is double (600mg). Can be self-injected."
  },
  {
    externalId: "BIO-006",
    name: "Tezepelumab",
    genericName: "Tezepelumab",
    brandNames: "Tezspire",
    category: "Biologic",
    subCategory: "Anti-TSLP",
    route: "Subcutaneous injection",
    standardDose: "210mg every 4 weeks",
    availableStrengths: "210mg prefilled syringe/autoinjector",
    defaultFrequency: "Every 4 weeks",
    indicatedFor: "Severe Asthma (all phenotypes — not limited to eosinophilic)",
    rxOtc: "Rx",
    clinicalNotes: "Only biologic NOT requiring eosinophil/IgE/allergy status. Works upstream of the inflammatory cascade. Can be self-injected."
  },
  {
    externalId: "BIO-007",
    name: "Tralokinumab",
    genericName: "Tralokinumab",
    brandNames: "Adbry",
    category: "Biologic",
    subCategory: "Anti-IL-13",
    route: "Subcutaneous injection",
    standardDose: "600mg loading, then 300mg every 2 weeks (or 4 weeks if controlled)",
    availableStrengths: "150mg prefilled syringe",
    defaultFrequency: "Every 2-4 weeks",
    indicatedFor: "Moderate-Severe Atopic Dermatitis",
    rxOtc: "Rx",
    clinicalNotes: "Targets IL-13 specifically. For atopic dermatitis — relevant for allergic patients with comorbid eczema."
  },
  {
    externalId: "BIO-008",
    name: "Itepekimab",
    genericName: "Itepekimab",
    brandNames: "Dupixent (pipeline)",
    category: "Biologic",
    subCategory: "Anti-IL-33",
    route: "Subcutaneous injection",
    standardDose: "Phase 3 — 300mg every 2-4 weeks",
    availableStrengths: "300mg (investigational)",
    defaultFrequency: "Every 2-4 weeks",
    indicatedFor: "Severe Asthma, Atopic Dermatitis (pipeline)",
    rxOtc: "Rx",
    clinicalNotes: "In development — upstream cytokine inhibition."
  },
  {
    externalId: "BIO-009",
    name: "Cendakimab",
    genericName: "Cendakimab",
    brandNames: "Pipeline",
    category: "Biologic",
    subCategory: "Anti-IL-13Rα2",
    route: "Oral (small molecule)",
    standardDose: "Investigational oral dosing",
    availableStrengths: "TBD",
    defaultFrequency: "Once daily (investigational)",
    indicatedFor: "Eosinophilic Esophagitis, Atopic Dermatitis, Asthma (pipeline)",
    rxOtc: "Rx",
    clinicalNotes: "Oral biologic-like small molecule — in development."
  },
  {
    externalId: "MC-001",
    name: "Cromolyn Sodium",
    genericName: "Cromolyn Sodium",
    brandNames: "NasalCrom",
    category: "Mast Cell Stabilizer",
    subCategory: "Intranasal",
    route: "Intranasal",
    standardDose: "1 spray per nostril 3-6x daily",
    availableStrengths: "5.2mg/spray",
    defaultFrequency: "3-6 times daily",
    indicatedFor: "Allergic Rhinitis (prevention)",
    rxOtc: "OTC",
    clinicalNotes: "Must be used before allergen exposure — prophylactic only. Very safe, good for children."
  },
  {
    externalId: "MC-002",
    name: "Cromolyn Sodium Inhaler",
    genericName: "Cromolyn Sodium",
    brandNames: "Intal",
    category: "Mast Cell Stabilizer",
    subCategory: "Inhaled",
    route: "Inhaled (MDI/Nebulizer)",
    standardDose: "2 puffs 4x daily (prophylaxis); 2 puffs before exercise",
    availableStrengths: "1mg/spray (MDI); 20mg/2mL (nebulizer)",
    defaultFrequency: "4 times daily",
    indicatedFor: "Mild Persistent Asthma (prophylaxis), EIB",
    rxOtc: "Rx",
    clinicalNotes: "Largely replaced by ICS but very safe. Good for exercise-induced bronchoconstriction."
  },
  {
    externalId: "MC-003",
    name: "Nedocromil",
    genericName: "Nedocromil Sodium",
    brandNames: "Alocril (ophthalmic)",
    category: "Mast Cell Stabilizer",
    subCategory: "Ophthalmic",
    route: "Ophthalmic",
    standardDose: "1-2 drops per eye twice daily",
    availableStrengths: "2% solution",
    defaultFrequency: "Twice daily",
    indicatedFor: "Allergic Conjunctivitis",
    rxOtc: "Rx",
    clinicalNotes: "Ophthalmic — for eye symptoms of allergic rhinitis."
  },
  {
    externalId: "MC-004",
    name: "Ketotifen",
    genericName: "Ketotifen Fumarate",
    brandNames: "Zaditor, Alaway (ophthalmic)",
    category: "Mast Cell Stabilizer",
    subCategory: "Ophthalmic / Oral",
    route: "Ophthalmic/Oral",
    standardDose: "Ophthalmic: 1 drop per eye twice daily",
    availableStrengths: "0.025% ophthalmic; 1mg oral tablet",
    defaultFrequency: "Twice daily",
    indicatedFor: "Allergic Conjunctivitis, Urticaria (oral)",
    rxOtc: "OTC (ophthalmic)",
    clinicalNotes: "Dual antihistamine + mast cell stabilizer. Oral form used in some countries for urticaria."
  },
  {
    externalId: "EP-001",
    name: "Epinephrine Auto-Injector",
    genericName: "Epinephrine (Adrenaline)",
    brandNames: "EpiPen, EpiPen Jr, Auvi-Q, Adrenaclick",
    category: "Epinephrine",
    subCategory: "Anaphylaxis Rescue",
    route: "Intramuscular (auto-injector)",
    standardDose: "0.3mg IM (adults ≥30kg); 0.15mg IM (children 15-30kg)",
    availableStrengths: "0.15mg, 0.3mg auto-injector",
    defaultFrequency: "As needed (anaphylaxis emergency)",
    indicatedFor: "Anaphylaxis, Severe Allergic Reaction",
    rxOtc: "Rx",
    clinicalNotes: "⚠️ CRITICAL SAFETY MEDICATION. All allergy patients should have 2 auto-injectors. Inject into outer thigh. Call 911 after use."
  },
  {
    externalId: "EP-002",
    name: "Epinephrine Nasal Spray",
    genericName: "Epinephrine",
    brandNames: "Neffy",
    category: "Epinephrine",
    subCategory: "Anaphylaxis Rescue",
    route: "Intranasal",
    standardDose: "One 2mg spray per nostril",
    availableStrengths: "2mg/0.1mL intranasal",
    defaultFrequency: "As needed (anaphylaxis emergency)",
    indicatedFor: "Anaphylaxis",
    rxOtc: "Rx",
    clinicalNotes: "⚠️ New FDA-approved (2023) intranasal epinephrine. Alternative to auto-injector for patients unable to use injector."
  },
  {
    externalId: "AI-001",
    name: "Subcutaneous Immunotherapy",
    genericName: "Allergen extracts (custom)",
    brandNames: "SCIT (allergy shots)",
    category: "Immunotherapy",
    subCategory: "Subcutaneous AIT",
    route: "Subcutaneous injection",
    standardDose: "Build-up: weekly injections increasing dose. Maintenance: 0.5mL every 4-8 weeks",
    availableStrengths: "Custom vials (1:100 to 1:10 dilutions)",
    defaultFrequency: "Weekly (build-up), Monthly (maintenance)",
    indicatedFor: "Allergic Rhinitis, Allergic Asthma, Stinging Insect Allergy, Atopic Dermatitis",
    rxOtc: "Rx",
    clinicalNotes: "Gold standard — modifies disease. 3-5 year course. Must be administered in medical office with epinephrine available."
  },
  {
    externalId: "AI-002",
    name: "Sublingual Immunotherapy — Dust Mite",
    genericName: "Dermatophagoides pteronyssinus/farinae",
    brandNames: "Odactra",
    category: "Immunotherapy",
    subCategory: "Sublingual AIT",
    route: "Sublingual tablet",
    standardDose: "1 tablet (12 SQ-HDM) dissolved under tongue once daily",
    availableStrengths: "12 SQ-HDM tablet",
    defaultFrequency: "Once daily",
    indicatedFor: "House Dust Mite Allergic Rhinitis",
    rxOtc: "Rx",
    clinicalNotes: "First dose in medical office (30 min observation). Self-administered daily thereafter. 3-year course."
  },
  {
    externalId: "AI-003",
    name: "Sublingual Immunotherapy — Grass",
    genericName: "Timothy grass pollen",
    brandNames: "Grastek",
    category: "Immunotherapy",
    subCategory: "Sublingual AIT",
    route: "Sublingual tablet",
    standardDose: "1 tablet (2800 BAU) dissolved under tongue once daily",
    availableStrengths: "2800 BAU",
    defaultFrequency: "Once daily (start 4 months before grass season)",
    indicatedFor: "Grass Pollen Allergic Rhinitis",
    rxOtc: "Rx",
    clinicalNotes: "Seasonal — start 4 months before grass pollen season. First dose in office."
  },
  {
    externalId: "AI-004",
    name: "Sublingual Immunotherapy — Ragweed",
    genericName: "Artemisia artemisiifolia",
    brandNames: "Ragwitek",
    category: "Immunotherapy",
    subCategory: "Sublingual AIT",
    route: "Sublingual tablet",
    standardDose: "1 tablet (12 Amb a 1-U) dissolved under tongue once daily",
    availableStrengths: "12 Amb a 1-U",
    defaultFrequency: "Once daily (start 12 weeks before ragweed season)",
    indicatedFor: "Ragweed Pollen Allergic Rhinitis",
    rxOtc: "Rx",
    clinicalNotes: "Start 12 weeks before ragweed season. First dose in office."
  },
  {
    externalId: "AI-005",
    name: "Oral Immunotherapy — Peanut",
    genericName: "Peanut allergen powder",
    brandNames: "Palforzia",
    category: "Immunotherapy",
    subCategory: "Oral Food IT",
    route: "Oral (with food)",
    standardDose: "Build-up dose: 3mg-300mg. Maintenance: 300mg daily (with food)",
    availableStrengths: "0.5mg, 1mg, 10mg, 20mg, 100mg, 300mg packets",
    defaultFrequency: "Daily (maintenance)",
    indicatedFor: "Peanut Allergy (ages 4-17)",
    rxOtc: "Rx",
    clinicalNotes: "FDA-approved oral immunotherapy for peanut allergy. Desensitizes, does not cure. Ongoing daily maintenance required."
  },
  {
    externalId: "SLIT-001",
    name: "SLIT Drops — House Dust Mite",
    genericName: "Dermatophagoides pteronyssinus + D. farinae extracts",
    brandNames: "Custom compounded (ALK, Greer, Stallergenes, Allergy Labs)",
    category: "Immunotherapy",
    subCategory: "SLIT-Drops Custom",
    route: "Sublingual drops",
    standardDose: "Build-up: 1-5 drops increasing concentration once daily. Maintenance: 5 drops maintenance vial — hold 1-2 min under tongue before swallowing",
    availableStrengths: "Vials: 1:2000, 1:200, 1:20, 1:2 dilution (compounded per patient)",
    defaultFrequency: "Once daily",
    indicatedFor: "House Dust Mite Allergic Rhinitis, Allergic Asthma, Atopic Dermatitis",
    rxOtc: "Rx",
    clinicalNotes: "Off-label in US but widely prescribed. Custom compounded per allergy test. First dose in office recommended. 3-5 year course. Refrigerate vials."
  },
  {
    externalId: "SLIT-002",
    name: "SLIT Drops — Grass Pollen Mix",
    genericName: "Bermuda, Timothy, Orchard, Rye, Kentucky Blue grass extracts",
    brandNames: "Custom compounded (ALK, Greer, Allergy Labs)",
    category: "Immunotherapy",
    subCategory: "SLIT-Drops Custom",
    route: "Sublingual drops",
    standardDose: "Build-up: 1-5 drops increasing concentration once daily. Maintenance: 5 drops maintenance vial once daily",
    availableStrengths: "Vials: 1:2000, 1:200, 1:20, 1:2 dilution (compounded per patient)",
    defaultFrequency: "Once daily",
    indicatedFor: "Grass Pollen Allergic Rhinitis, Allergic Asthma",
    rxOtc: "Rx",
    clinicalNotes: "Pre-season start recommended. Custom mixed per skin test or IgE. Off-label in US."
  },
  {
    externalId: "SLIT-003",
    name: "SLIT Drops — Tree Pollen Mix",
    genericName: "Oak, Birch, Cedar, Maple, Elm, Walnut pollen extracts",
    brandNames: "Custom compounded (ALK, Greer, Allergy Labs)",
    category: "Immunotherapy",
    subCategory: "SLIT-Drops Custom",
    route: "Sublingual drops",
    standardDose: "Build-up: 1-5 drops increasing concentration once daily. Maintenance: 5 drops maintenance vial once daily",
    availableStrengths: "Vials: 1:2000, 1:200, 1:20, 1:2 dilution (compounded per patient)",
    defaultFrequency: "Once daily",
    indicatedFor: "Tree Pollen Allergic Rhinitis, Allergic Asthma",
    rxOtc: "Rx",
    clinicalNotes: "Tree mix composition varies by region. Compounded per patient sensitization profile."
  },
  {
    externalId: "SLIT-004",
    name: "SLIT Drops — Weed Pollen Mix",
    genericName: "Ragweed, Mugwort, English Plantain, Russian Thistle extracts",
    brandNames: "Custom compounded (ALK, Greer, Allergy Labs)",
    category: "Immunotherapy",
    subCategory: "SLIT-Drops Custom",
    route: "Sublingual drops",
    standardDose: "Build-up: 1-5 drops increasing concentration once daily. Maintenance: 5 drops maintenance vial once daily",
    availableStrengths: "Vials: 1:2000, 1:200, 1:20, 1:2 dilution (compounded per patient)",
    defaultFrequency: "Once daily",
    indicatedFor: "Weed Pollen Allergic Rhinitis, Allergic Asthma",
    rxOtc: "Rx",
    clinicalNotes: "Ragweed dominant eastern US. Mugwort in western US. Custom per regional allergen profile."
  },
  {
    externalId: "SLIT-005",
    name: "SLIT Drops — Cat/Dog Dander",
    genericName: "Felis domesticus (cat) and/or Canis familiaris (dog) epithelium extracts",
    brandNames: "Custom compounded (ALK, Greer, Allergy Labs)",
    category: "Immunotherapy",
    subCategory: "SLIT-Drops Custom",
    route: "Sublingual drops",
    standardDose: "Build-up: 1-5 drops increasing concentration once daily. Maintenance: 5 drops maintenance vial once daily",
    availableStrengths: "Vials: 1:2000, 1:200, 1:20, 1:2 dilution (compounded per patient)",
    defaultFrequency: "Once daily",
    indicatedFor: "Pet Dander Allergic Rhinitis, Allergic Asthma, Atopic Dermatitis",
    rxOtc: "Rx",
    clinicalNotes: "Most requested custom SLIT — many patients sensitized to pets they live with. Cat and dog can be combined or separate vials."
  },
  {
    externalId: "SLIT-006",
    name: "SLIT Drops — Mold Mix",
    genericName: "Alternaria, Cladosporium, Aspergillus, Helminthosporium extracts",
    brandNames: "Custom compounded (ALK, Greer, Allergy Labs)",
    category: "Immunotherapy",
    subCategory: "SLIT-Drops Custom",
    route: "Sublingual drops",
    standardDose: "Build-up: 1-5 drops increasing concentration once daily. Maintenance: 5 drops maintenance vial once daily",
    availableStrengths: "Vials: 1:2000, 1:200, 1:20, 1:2 dilution (compounded per patient)",
    defaultFrequency: "Once daily",
    indicatedFor: "Mold Allergic Rhinitis, Mold-Sensitive Asthma",
    rxOtc: "Rx",
    clinicalNotes: "Alternaria most clinically significant. Mold-sensitive asthma can be severe. Treat cautiously — mold extracts less standardized."
  },
  {
    externalId: "SLIT-007",
    name: "SLIT Drops — Cockroach",
    genericName: "Blattella germanica (German cockroach) extract",
    brandNames: "Custom compounded (ALK, Greer)",
    category: "Immunotherapy",
    subCategory: "SLIT-Drops Custom",
    route: "Sublingual drops",
    standardDose: "Build-up: 1-5 drops increasing concentration once daily. Maintenance: 5 drops maintenance vial once daily",
    availableStrengths: "Vials: 1:2000, 1:200, 1:20, 1:2 dilution (compounded per patient)",
    defaultFrequency: "Once daily",
    indicatedFor: "Cockroach Allergic Rhinitis, Allergic Asthma (urban populations)",
    rxOtc: "Rx",
    clinicalNotes: "Highly relevant in urban/inner-city populations. Major driver of pediatric asthma in inner cities."
  },
  {
    externalId: "SLIT-008",
    name: "SLIT Drops — Multi-Allergen Custom Mix",
    genericName: "Custom combination of patient-specific allergen extracts (2-8 allergens)",
    brandNames: "Custom compounded per clinician Rx (ALK, Greer, Stallergenes, Allergy Labs)",
    category: "Immunotherapy",
    subCategory: "SLIT-Drops Custom",
    route: "Sublingual drops",
    standardDose: "Clinician-prescribed schedule. Typically 3-vial set. 3-5 drops Vial 1 → build up → 5 drops Vial 3 (maintenance). Hold 1-2 min under tongue.",
    availableStrengths: "Vial 1 (1:2000), Vial 2 (1:200), Vial 3 (1:20) maintenance — all custom compounded",
    defaultFrequency: "Once daily",
    indicatedFor: "Multi-Allergen Sensitization — Allergic Rhinitis, Allergic Asthma, Atopic Dermatitis",
    rxOtc: "Rx",
    clinicalNotes: "Most common SLIT prescription. Combines patient's top sensitizations (e.g. dust mite + grass + cat) in one vial set. Dispensed as 3-vial build-up + maintenance set."
  }
];
