export const MEDICATION_FREQUENCIES = [
  "Once daily",
  "Once or twice daily",
  "Once daily (evening)",
  "Every 4-6 hours",
  "3-4 times daily",
  "Once daily (empty stomach)",
  "Twice daily",
  "Every 10-12 hours (max 3 days)",
  "Every 8-10 hours (max 3 days)",
  "Every 4 hours",
  "2-3 times daily",
  "4x daily (IR) or 2x daily (ER)",
  "Twice daily (or once daily for Ellipta)",
  "Twice daily (also MART strategy)",
  "Every 4-6 hours PRN",
  "Every 4-8 hours PRN",
  "Every 2-4 weeks",
  "Every 4 weeks",
  "Every 4 weeks (IV infusion)",
  "Every 4 weeks (loading) then every 8 weeks",
  "Every 2 weeks",
  "Once daily (investigational)",
  "3-6 times daily",
  "4 times daily",
  "As needed (anaphylaxis emergency)",
  "Weekly (build-up), Monthly (maintenance)",
  "Once daily (start 4 months before grass season)",
  "Once daily (start 12 weeks before ragweed season)",
  "Daily (maintenance)"
] as const;
